version: '3.7'

services:
  manager:
    image: nancode/dora
    ports:
      - '9000:9000'
    env_file: .env.production
    entrypoint: [ 'node', './manager/main.js' ]
    volumes:
      - ./uploads:/server/uploads

  process:
    image: nancode/dora
    env_file: .env.production
    entrypoint: [ 'node', './process/main.js' ]

  relay:
    image: nancode/dora
    ports:
      - '8000:8000'
    env_file: .env.production
    entrypoint: [ 'node', './relay/main.js' ]

  webapp:
    image: nancode/dora-app
    ports:
      - '9001:80'
    depends_on:
      - manager
