services:
  mysql:
    image: mysql:5.7.22
    container_name: mysql
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    ports:
      - '3306:3306'
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: default_password
      MYSQL_DATABASE: dora
    volumes:
      - dora-mysql:/var/lib/mysql

  redis:
    image: redis:6
    container_name: redis
    command: >
      --requirepass default_password
    ports:
      - '6379:6379'
    volumes:
      - dora-redis:/data

  zookeeper:
    image: 'bitnami/zookeeper:3.7'
    container_name: 'zookeeper'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - dora-zookeeper:/bitnami/zookeeper

  kafka:
    image: 'bitnami/kafka:3'
    container_name: 'kafka'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    volumes:
      - dora-kafka:/bitnami/kafka

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: elasticsearch
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      ES_JAVA_OPTS: '-Xmx1g -Xms1g'
      ELASTIC_PASSWORD: default_password
      discovery.type: single-node
      xpack.license.self_generated.type: 'basic'
      xpack.security.enabled: 'true'
      xpack.monitoring.collection.enabled: 'false'
    volumes:
      - dora-elasticsearch:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.0
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: default_password
    depends_on:
      - elasticsearch

volumes:
  dora-mysql:
  dora-redis:
  dora-zookeeper:
  dora-kafka:
  dora-elasticsearch:
