version: '3.7'

services:
  mysql:
    image: mysql:5.7.22
    container_name: mysql
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    ports:
      - '3306:3306'
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: default_password
      MYSQL_DATABASE: dora
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:6
    container_name: redis
    command: >
      --requirepass default_password
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: elasticsearch
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      ES_JAVA_OPTS: '-Xmx1g -Xms1g'
      ELASTIC_PASSWORD: default_password
      discovery.type: single-node
      cluster.name: "docker-cluster"
      network.host: '0.0.0.0'
      xpack.license.self_generated.type: 'basic'
      xpack.security.enabled: 'true'
      xpack.monitoring.collection.enabled: 'false'
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

volumes:
  mysql-data:
  redis-data:
  elasticsearch-data:
