version: '3.7'

services:
  postgres:
    image: postgres:12
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: bastion
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'

volumes:
  pgdata:
